[package]
name = "backgammon-contract"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
backgammon-core = { path = "../backgammon-core" }
backgammon-protocol = { path = "../backgammon-protocol" }
ciborium.workspace = true
freenet-scaffold.workspace = true
freenet-scaffold-macro.workspace = true
freenet-stdlib.workspace = true
serde.workspace = true

[features]
default = ["freenet-main-contract"]
freenet-main-contract = []

[dev-dependencies]
ed25519-dalek = { version = "3.0.0", default-features = false }
